apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    {{- include "helm-chart.labels" . | nindent 4 }}
  name: {{ include "helm-chart.fullname" . }}
spec:
  selector:
    matchLabels:
      {{- include "helm-chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "helm-chart.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - image: {{ .Values.image.repository }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        name: devops-project-1
        ports:
        - containerPort: 8080
          protocol: TCP
          name: http
        resources:
          requests:
            cpu: 100m
      tolerations:
      - effect: NoExecute
        key: node.kubernetes.io/not-ready
        operator: Exists
        tolerationSeconds: 300