apiVersion: v1
kind: Service
metadata:
  finalizers:
  - service.kubernetes.io/load-balancer-cleanup
  labels:
    {{- include "helm-chart.labels" . | nindent 4 }}
  name: {{ include "helm-chart.fullname" . }}
spec:
  ports:
  - port: {{ .Values.service.port }}
    protocol: TCP
    targetPort: http
    name: http
  selector:
    {{- include "helm-chart.selectorLabels" . | nindent 4 }}
  sessionAffinity: None
  type: {{ .Values.service.type }}