name: CI


on:
  pull_request:
    branches:
    - master


jobs:
  test_and_build:
    name: build and test lint
    
    runs-on: ubuntu-18.04

    strategy:
      matrix:
        node: [13.x, 14.x]
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Use NodeJS Version - ${{ matrix.node }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node }}
    - name: Install yarn
      run: npm i yarn -g
    - name: Install dependencies
      run: yarn
    - name: Check lint
      run: yarn test:lint
    - name: Build
      run: yarn build
