name: CD


on:
  push:
    branches:
    - master


env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  GKE_CLUSTER: sandbox
  GKE_ZONE: europe-west2-c
  DEPLOYMENT_NAME: node-app
  IMAGE: static-site



jobs:
  build_and_deploy:
    name: build and deploy
    
    runs-on: ubuntu-18.04

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: fetch the version of the application
      run: |
        ./fetchVersionAsEnvVar.sh
        echo $VERSION
    - name: Setup gcloud CLI
      uses: GoogleCloudPlatform/github-actions/setup-gcloud@0.1.3
      with:
        service_account_key: ${{ secrets.GKE_SA_KEY }}
        project_id: ${{ secrets.GKE_PROJECT }}
    - name: Auth google container registry 
      run: gcloud --quiet auth configure-docker
    - name: Setup kubectl CLI by fetching GKE credentials
      run: gcloud container clusters get-credentials "$GKE_CLUSTER" --zone "$GKE_ZONE"